tossmob_enabled: true
admin_only_mode: false

ranks:
  mods:
    - wolfang302
    - milkoe777
    - cole_dorais_17
    - bobaddie
    - zmorlan
  admins:
    - austindapro
    - spartan12233th
    - nerdygirl544
    - soccerkiff
    - mustardbukkit
  co_owners:
    - bees_knees
    - dethplaque
  owner:
    - smack17
  developer:
    - paldiu
    
bypass_bans:
  - smack17
  - dethplaque
  - bees_knees
  
chat_listener_permissions:
  - smack17
  - paldiu
  - dethplaque
  - bees_knees
  
parse_html_file_links:
  - TO BE ADDED
  
book:
  title: To be changed.
  page1: To be changed. Don't put more than 90 characters in the book.
  page2: To be changed. Don't put more than 90 characters in the book.
  page3: To be changed. Don't put more than 90 characters in the book.