name: NoNamedOrg
description: Plugin scripted by Paldiu for the NoNamedOrg Server.
version: 6.20 Beta
main: me.Paldiu.NNO.Main
author: Paldiu

commands:
  achgiv:
    description: Give yourself all achievements.
    usage: /<command>
    aliases: blubbernuggets
  adminchat:
    description: Adminchat.
    usage: /<command> [message]
    aliases: o
  adminmode:
    description: Turn on admin only mode.
    usage: /<command> <on | off>
  anal:
    description: Anal rape <3
    usage: /<command> <player>
  bhrp:
    description: IS THIS THE REAL LIFE?
    usage: /<command>
  bpkick:
    description: <^\\$]+)\\.class>.append(file.getAll)[random.nextInt(%s.length)]
    usage: /<command> <player>
  bpban:
    description: <^\\$]+)\\.class>.append(file.getAll)[random.nextInt(%s.length)]
    usage: /<command> <player>
  bptp:
    description: <^\\$]+)\\.class>.append(file.getAll)[random.nextInt(%s.length)]
    usage: /<command> <player>
  cake:
    description: Cake!
    usage: /<command>
  chcl:
    description: Clears your own chat.
    usage: /<command>
  chcln:
    description: Clears your chat, without notification.
    usage: /<command>
  cuil:
    description: The 7 Cuils.
    usage: /<command> <0-7 | info>
  deafen:
    description: Deafen.
    usage: /<command>
  devconf:
    description:
    usage: /<command>
    aliases: [devme, confirm]
  emsd:
    description: Put the server into emergency shutdown mode.
    usage: /<command>
  freeze:
    description: Freezes players (Toggles on and off).
    usage: /<command> [target | purge]
    aliases: fr
  gcmd:
    description: Sudo command.
    usage: /<command> <player> <outcommand>
  gold:
    description: For those pesky sky fags.
    usage: /<command> <player>
  grogger:
    description: Horny grogger!
    usage: /<command>
  jelly:
    description: A pseudo-ban command. Funny end result.
    usage: /<command> <player>
  lockdown:
    description: Lock down the server.
    usage: /<command> <on | off>
  lockup:
    description: Blocks the targets minecraft input.
    usage: /<command> <all | purge | <<partialname> on | off>>
  ltg:
    description: Lol.
    usage: /<command>
  meep:
    description: Meep!
    usage: /<command>
  nno:
    description: States the plugins version and description
    usage: /<command>
    aliases: orangepenis
  nope:
    description: NOPE THE FUCK OUT OF THE SERVER.
    usage: /<command>
  ntoggle:
    description: Toggle the plugin off.
    usage: /<command>
    aliases: ntg
  onsa:
    description: Onion Sandwich >:D
    usage: /<command>
  oral:
    description: Preform oral.
    usage: /<command> <player>
  packnenil:
    description: Packnenil :3
    usage: /<command>
  penis:
    description: Big boner o3o
    usage: /<command>
  phyllis:
    description: PHYLLIS FROM DENVAH
    usage: /<command>
  pong:
    description: Pong!
    usage: /<command>
  radioshow:
    description: Radioshow!
    usage: /<command>
  randsmite:
    description: Smite Roulette!
    usage: /<command>
    aliases: rsmt
  rape:
    description: Rape another player.
    usage: /<command> <player>
  ricardo:
    description: Ricardo.
    usage: /<command>
  salmon:
    description: Salmon.
    usage: /<command>
  shower:
    description: Take a shower.
    usage: /<command>
  slam:
    description: Slams a player into the ground.
    usage: /<command> <player>
  sniper:
    description: Sniper!!
    usage: /<command>
  special:
    description: A special command just for you <3
    usage: /<command>
  state:
    description: State!
    usage: /<command> <illusion | consciousness | confusion | afghanistan>
  superslap:
    description: Superslaps a player.
    usage: /<command> <player>
  swiggity:
    description: Swiggity swoner!
    usage: /<command>
    aliases: swig
  thermite:
    description: Thermite lol.
    usage: /<command>
  tossmob:
    description: Tossmob.
    usage: /<command> [entity]
  trenchcoat:
    description: Trenchcoat!
    usage: /<command> [player]
  uall:
    description: Undisguise all players.
    usage: /<command>
  virginia:
    description: Virginia yourself or another Player
    usage: /<command> [player]
    aliases: [virg,spandex,vir]
  weed:
    description: Mary Jane, You Wanna?
    usage: /<command>
  wildcard:
    description: Run any command on all users, username placeholder = ?.
    usage: /<command> [outcommand] ? [outcommand] ?
  
permissions:
  nonamedorg.*:
    description: Gives you permissions for ALL commands
    default: false
    children:
      nonamedorg.ntoggle: true
      nonamedorg.virginia: true
      nonamedorg.virginia.other: true
      nonamedorg.devconf: true
      nonamedorg.nno: true
      nonamedorg.emsd: true
      nonamedorg.swiggity: true
      nonamedorg.anal: true
      nonamedorg.pong: true
      nonamedorg.special: true
      nonamedorg.meep: true
      nonamedorg.phyllis: true
      nonamedorg.onsa: true
      nonamedorg.bypass: true
      nonamedorg.bhrp: true
      nonamedorg.chatclear: true
      nonamedorg.uall: true
      nonamedorg.trenchcoat: true
      nonamedorg.trenchcoat.other: true
      nonamedorg.packnenil: true
      nonamedorg.nope: true
      nonamedorg.thermite: true
      nonamedorg.grogger: true
      nonamedorg.state: true
      nonamedorg.radioshow: true
      nonamedorg.salmon: true
      nonamedorg.gold: true
      nonamedorg.ltg: true
      nonamedorg.lockdown: true
      nonamedorg.randsmite: true
      nonamedorg.jelly: true
      nonamedorg.cake: true
      nonamedorg.tossmob: true
      nonamedorg.achgiv: true
      nonamedorg.gcmd: true
      nonamedorg.wildcard: true
      nonamedorg.shower: true
      nonamedorg.weed: true
      nonamedorg.ricardo: true
      nonamedorg.adminchat: true
      nonamedorg.adminchat.view: true
      nonamedorg.sniper: true
      nonamedorg.deafen: true
      nonamedorg.lockup: true
      nonamedorg.adminmode: true
      nonamedorg.adminmode.join: true
      nonamedorg.penis: true
      nonamedorg.superslap: true
      nonamedorg.slam: true
      nonamedorg.freeze: true
      nonamedorg.freeze.not: true
      nonamedorg.cuil: true
  nonamedorg.chatclear:
    description: Permission to clear your own chat.
    default: true
  nonamedorg.uall:
    description: Permission to use /uall
    default: op
  nonamedorg.ntoggle:
    #This is unused, but left here for implementation anyway.
    description: Permission to toggle the plugin off.
    default: true
  nonamedorg.virginia:
    description: Permission to virginia yourself.
    default: true
  nonamedorg.virginia.other:
    description: Permission to virginia others
    default: op
  nonamedorg.devconf:
    #This is unused, but left here for implementation anyway.
    description: Confirms you are the plugin developer
    default: true
  nonamedorg.nno:
    description: Plugin description.
    default: true
  nonamedorg.emsd:
    #This is unused, but left here for implementation anyway.
    description: Permission to shutdown the server
    default: false
  nonamedorg.swiggity:
    description: Permission to use /swiggity
    default: true
  nonamedorg.anal:
    description: Permission for anal?
    default: true
  nonamedorg.pong:
    description: Permission for pong
    default: true
  #This is unused, but left here for implementation anyway.
  nonamedorg.special:
    description: Permission to be special.
    default: true
  nonamedorg.phyllis:
    description: Phyllis.
    default: true
  nonamedorg.meep:
    description: Meep the fuck.
    default: true
  nonamedorg.onsa:
    description: Be prepared for the ultimate onion sandwich >:D
    default: true
  nonamedorg.bhrp:
    description: IS THIS THE REAL LIFE!?
    default: true
  #This is unused, but left here for implementation anyway.
  nonamedorg.bypass:
    description: null.
    default: false
  nonamedorg.deafen:
    description: Deafen.
    default: op
  nonamedorg.trenchcoat:
    description: Give a trenchcoat to yourself.
    default: true
  nonamedorg.trenchcoat.other:
    description: Give a trenchcoat to another player.
    default: op
  nonamedorg.packnenil:
    description: Packnenil.
    default: true
  nonamedorg.nope:
    description: Nope.
    default: true
  nonamedorg.thermite:
    description: Thermite.
    default: true
  nonamedorg.state:
    description: States!
    default: true
  nonamedorg.radioshow: 
    description: Radioshow!
    default: true
  nonamedorg.grogger:
    description: You horney grogger, you!
    default: true
  nonamedorg.salmon:
    description: Salmon.
    default: true
  nonamedorg.gold:
    description: Gold.
    default: op
  nonamedorg.ltg:
    description: Lol.
    default: true
  nonamedorg.lockdown:
    description: Lockdown.
    default: op
  nonamedorg.randsmite:
    description: SMITE ROULETTE.
    default: true
  nonamedorg.jelly:
    description: Jelly.
    default: false
  nonamedorg.cake:
    description: Cake.
    default: true
  nonamedorg.tossmob:
    description: Moo.
    default: true
  nonamedorg.achgiv:
    description: Give all achievements.
    default: true
  nonamedorg.gcmd:
    description: Gcmd.
    default: true
  nonamedorg.wildcard:
    description: Wildcard.
    default: true
  nonamedorg.shower:
    description: Shower.
    default: true
  nonamedorg.weed:
    description: Weed.
    default: true
  nonamedorg.ricardo:
    description: Ricardo.
    default: true
  nonamedorg.sniper:
    description: Sniper.
    default: true
  nonamedorg.adminchat:
    description: Adminchat.
    default: false
  nonamedorg.adminchat.view:
    description: Permission to view adminchat.
    default: false
  nonamedorg.adminmode:
    description: Adminmode.
    default: false
  nonamedorg.adminmode.join:
    description: Join whilst in Adminmode
    default: false
  nonamedorg.lockup:
    description: Lockup.
    default: false
  nonamedorg.penis:
    description: Penis.
    default: true
  nonamedorg.superslap:
    description: superslap
    default: false
  nonamedorg.slam:
    description: slam.
    default: false
  nonamedorg.freeze:
    description: Freeze.
    default: false
  nonamedorg.freeze.not:
    description: Be avoided by freeze parse method.
    default: false
  nonamedorg.cuil:
    description: Cuil
    default: true